/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const QuestionId = IDL.Nat;
export const Question = IDL.Record({
  'id' : QuestionId,
  'correctIndex' : IDL.Nat,
  'text' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
});
export const AnswerSubmission = IDL.Record({ 'answers' : IDL.Vec(IDL.Nat) });
export const QuizResult = IDL.Record({
  'score' : IDL.Nat,
  'totalQuestions' : IDL.Nat,
  'incorrectCount' : IDL.Nat,
  'correctCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
  'submitAnswers' : IDL.Func([AnswerSubmission], [QuizResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const QuestionId = IDL.Nat;
  const Question = IDL.Record({
    'id' : QuestionId,
    'correctIndex' : IDL.Nat,
    'text' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
  });
  const AnswerSubmission = IDL.Record({ 'answers' : IDL.Vec(IDL.Nat) });
  const QuizResult = IDL.Record({
    'score' : IDL.Nat,
    'totalQuestions' : IDL.Nat,
    'incorrectCount' : IDL.Nat,
    'correctCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'getQuestions' : IDL.Func([], [IDL.Vec(Question)], ['query']),
    'submitAnswers' : IDL.Func([AnswerSubmission], [QuizResult], []),
  });
};

export const init = ({ IDL }) => { return []; };