/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnswerSubmission { 'answers' : Array<bigint> }
export interface Question {
  'id' : QuestionId,
  'correctIndex' : bigint,
  'text' : string,
  'options' : Array<string>,
}
export type QuestionId = bigint;
export interface QuizResult {
  'score' : bigint,
  'totalQuestions' : bigint,
  'incorrectCount' : bigint,
  'correctCount' : bigint,
}
export interface _SERVICE {
  'getQuestions' : ActorMethod<[], Array<Question>>,
  'submitAnswers' : ActorMethod<[AnswerSubmission], QuizResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];